### Получение списка сотрудников
GET http://localhost:8080/employees

### Добавление сотрудника 1
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Test",
  "department": 1,
  "salary": 1000
}

### Добавление сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test2",
  "lastName": "Test2",
  "department": 3,
  "salary": 4000
}

### Добавление сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Test3",
  "lastName": "Test3",
  "department": 2,
  "salary": 8000
}

### Получение суммы зарплат сотрудников
GET http://localhost:8080/employee/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employee/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employee/salary/max

### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employee/high-salary